/* AZ Restaurant Partners — trilingual engine (EN / हिंदी / اردو)
   Translations are machine-assisted drafts — have a native speaker review before launch. */
(function () {
  const norm = (s) => s.replace(/\s+/g, ' ').trim();

  // [ english(innerHTML) , hindi , urdu ]
  const ROWS = [
    // NAV
    [`How we work`, `हम कैसे काम करते हैं`, `ہم کیسے کام کرتے ہیں`],
    [`What's possible`, `क्या मुमकिन है`, `کیا ممکن ہے`],
    [`Find your fit`, `अपने लिए सही चुनें`, `اپنے لیے صحیح چنیں`],
    [`Book a free call`, `मुफ़्त कॉल बुक करें`, `مفت کال بُک کریں`],

    // HERO
    [`For the independent, family-run restaurant · Spring &amp; Greater Houston, TX`, `आज़ाद, परिवार-संचालित रेस्तराँ के लिए · स्प्रिंग और ग्रेटर ह्यूस्टन, TX`, `خود مختار، خاندانی ریستوران کے لیے · اسپرنگ اور گریٹر ہیوسٹن، TX`],
    [`You're working harder than ever. <em>So why is someone else keeping the profit?</em>`, `आप पहले से ज़्यादा मेहनत कर रहे हैं। <em>फिर मुनाफ़ा कोई और क्यों रख रहा है?</em>`, `آپ پہلے سے زیادہ محنت کر رہے ہیں۔ <em>پھر منافع کوئی اور کیوں رکھ رہا ہے؟</em>`],
    [`You're in before sunrise and out long after close. Your food beats the chain down the road — yet the delivery apps skim a third of every order and keep the customer you worked to earn, the phone rings through the dinner rush with no one free to answer, and a dozen systems you never asked for eat the hours you don't have. You're running flat out, and somehow everyone gets paid before you do — you're working for everyone but yourself. We're a restaurant family who've lived exactly this, and we became the technology-and-strategy team the big chains have, for places like yours. <strong>We don't get paid until you're keeping more.</strong> One free call, and you'll know exactly where your money's been hiding.`, `आप सूरज निकलने से पहले काम पर होते हैं और बंद होने के देर बाद तक। आपका खाना सड़क के उस पार वाली चेन से बेहतर है — फिर भी डिलीवरी ऐप्स हर ऑर्डर का एक-तिहाई हिस्सा ले जाते हैं और वह ग्राहक भी रख लेते हैं जिसे आपने मेहनत से कमाया, डिनर की भीड़ में फ़ोन बजता रहता है पर उठाने वाला कोई नहीं, और दर्जनों ऐसे सिस्टम जो आपने कभी माँगे ही नहीं, आपके वे घंटे खा जाते हैं जो आपके पास हैं ही नहीं। आप पूरी ताक़त से लगे हैं, और फिर भी हर किसी को आपसे पहले पैसे मिल जाते हैं — आप सबके लिए काम कर रहे हैं, बस अपने लिए नहीं। हम एक रेस्तराँ परिवार हैं जिसने ठीक यही सब झेला है, और हमने वही टेक्नोलॉजी-और-रणनीति टीम बनाई जो बड़ी चेन के पास होती है, आप जैसी जगहों के लिए। <strong>जब तक आप ज़्यादा बचाना शुरू न करें, हम पैसे नहीं लेते।</strong> बस एक मुफ़्त कॉल, और आप जान जाएँगे कि आपका पैसा असल में कहाँ छिपा है।`, `آپ سورج نکلنے سے پہلے کام پر ہوتے ہیں اور بند ہونے کے کافی بعد تک۔ آپ کا کھانا سڑک کے اُس پار والی چین سے بہتر ہے — پھر بھی ڈیلیوری ایپس ہر آرڈر کا ایک تہائی حصہ لے جاتی ہیں اور وہ گاہک بھی رکھ لیتی ہیں جسے آپ نے محنت سے کمایا، ڈنر کی بھیڑ میں فون بجتا رہتا ہے پر اٹھانے والا کوئی نہیں، اور درجنوں ایسے سسٹم جو آپ نے کبھی مانگے ہی نہیں، آپ کے وہ گھنٹے کھا جاتے ہیں جو آپ کے پاس ہیں ہی نہیں۔ آپ پوری طاقت سے لگے ہیں، اور پھر بھی ہر کسی کو آپ سے پہلے پیسے مل جاتے ہیں — آپ سب کے لیے کام کر رہے ہیں، بس اپنے لیے نہیں۔ ہم ایک ریستوران خاندان ہیں جس نے بالکل یہی سب جھیلا ہے، اور ہم نے وہی ٹیکنالوجی-اور-حکمتِ عملی ٹیم بنائی جو بڑی چینز کے پاس ہوتی ہے، آپ جیسی جگہوں کے لیے۔ <strong>جب تک آپ زیادہ بچانا شروع نہ کریں، ہم پیسے نہیں لیتے۔</strong> بس ایک مفت کال، اور آپ جان جائیں گے کہ آپ کا پیسہ اصل میں کہاں چھپا ہے۔`],
    [`Book your free call`, `अपनी मुफ़्त कॉल बुक करें`, `اپنی مفت کال بُک کریں`],
    [`Find your fit <span aria-hidden="true">→</span>`, `अपने लिए सही चुनें <span aria-hidden="true">→</span>`, `اپنے لیے صحیح چنیں <span aria-hidden="true">→</span>`],
    [`Abbas Zoeb — Founder &amp; Operator`, `अब्बास ज़ोएब — संस्थापक और संचालक`, `عباس ذوئب — بانی و آپریٹر`],

    // CREDS
    [`A restaurant family`, `एक रेस्तराँ परिवार`, `ایک ریستوران خاندان`],
    [`15+ years in hospitality — Canada, India &amp; Texas`, `15+ साल का हॉस्पिटैलिटी अनुभव — कनाडा, भारत और टेक्सस`, `ہاسپٹیلٹی میں 15+ سال — کینیڈا، انڈیا اور ٹیکساس`],
    [`We run our own`, `हमारा अपना रेस्तराँ`, `ہمارا اپنا ریستوران`],
    [`Wok &amp; Karahi, Houston — highly rated &amp; profitable every year`, `Wok &amp; Karahi, ह्यूस्टन — बेहतरीन रेटिंग और हर साल मुनाफ़े में`, `Wok &amp; Karahi، ہیوسٹن — اعلیٰ ریٹنگ اور ہر سال منافع میں`],
    [`Serious tech, on your side`, `मज़बूत टेक, आपके साथ`, `مضبوط ٹیک، آپ کے ساتھ`],
    [`The same engineers big companies rely on — building for your restaurant`, `वही इंजीनियर जिन पर बड़ी कंपनियाँ भरोसा करती हैं — आपके रेस्तराँ के लिए`, `وہی انجینئر جن پر بڑی کمپنیاں بھروسا کرتی ہیں — آپ کے ریستوران کے لیے`],
    [`Only on your side`, `सिर्फ़ आपकी तरफ़`, `صرف آپ کی طرف`],
    [`We take no app or vendor commissions`, `हम किसी ऐप या वेंडर से कमीशन नहीं लेते`, `ہم کسی ایپ یا وینڈر سے کمیشن نہیں لیتے`],

    // BAND
    [`Here's where the money actually goes.`, `पैसा असल में कहाँ जाता है, देखिए।`, `پیسہ اصل میں کہاں جاتا ہے، دیکھیے۔`],
    [`You cook the food — then watch the money walk out the door:`, `आप खाना बनाते हैं — और फिर पैसा दरवाज़े से बाहर जाते देखते हैं:`, `آپ کھانا بناتے ہیں — اور پھر پیسہ دروازے سے باہر جاتے دیکھتے ہیں:`],
    [`The app keeps <strong>15–30%</strong> of the order — some nights more than you make.`, `ऐप ऑर्डर का <strong>15–30%</strong> रख लेता है — कई रातों आपसे भी ज़्यादा।`, `ایپ آرڈر کا <strong>15–30%</strong> رکھ لیتا ہے — کئی راتوں آپ سے بھی زیادہ۔`],
    [`The guest who ordered is <strong>the app's customer, not yours</strong> — you can't even see your own regulars.`, `जिसने ऑर्डर किया वह <strong>ऐप का ग्राहक है, आपका नहीं</strong> — आप अपने नियमित ग्राहक तक नहीं देख पाते।`, `جس نے آرڈر کیا وہ <strong>ایپ کا گاہک ہے، آپ کا نہیں</strong> — آپ اپنے مستقل گاہک تک نہیں دیکھ پاتے۔`],
    [`The phone rings through dinner with <strong>no one free to grab it</strong>.`, `डिनर के बीच फ़ोन बजता रहता है पर <strong>उठाने वाला कोई नहीं</strong>।`, `ڈنر کے دوران فون بجتا رہتا ہے مگر <strong>اٹھانے والا کوئی نہیں</strong>۔`],
    [`Three tablets on the counter, <strong>re-keyed by hand</strong>.`, `काउंटर पर तीन टैबलेट, <strong>हाथ से दोबारा टाइप करते</strong>।`, `کاؤنٹر پر تین ٹیبلٹ، <strong>ہاتھ سے دوبارہ ٹائپ کرتے</strong>۔`],
    [`<em>None of it is permanent.</em> The apps are great for getting you <em>discovered</em> — the trick is not letting them keep the customer. We've done exactly this on our own restaurant, and we'll do it for yours: turn app guests into your own regulars, connect the right tools, and keep what you earn — and from the <strong>100+ tools out there</strong>, we bring you only the few that actually fit.`, `<em>यह सब हमेशा के लिए नहीं है।</em> ऐप्स आपको <em>नए लोगों तक पहुँचाने</em> में अच्छे हैं — असली बात है उन्हें ग्राहक रखने न देना। हमने यही अपने रेस्तराँ पर किया है, और आपके लिए भी करेंगे: ऐप के ग्राहकों को अपने नियमित ग्राहक बनाएँ, सही टूल जोड़ें, और अपनी कमाई अपने पास रखें — और <strong>100+ टूल्स में से</strong> हम सिर्फ़ वही चुनिंदा लाते हैं जो आप पर सही बैठें।`, `<em>یہ سب ہمیشہ کے لیے نہیں ہے۔</em> ایپس آپ کو <em>نئے لوگوں تک پہنچانے</em> میں اچھے ہیں — اصل بات ہے انہیں گاہک رکھنے نہ دینا۔ ہم نے یہی اپنے ریستوران پر کیا ہے، اور آپ کے لیے بھی کریں گے: ایپ کے گاہکوں کو اپنے مستقل گاہک بنائیں، صحیح ٹولز جوڑیں، اور اپنی کمائی اپنے پاس رکھیں — اور <strong>100+ ٹولز میں سے</strong> ہم صرف وہی چند لاتے ہیں جو آپ پر صحیح بیٹھیں۔`],

    // STATS
    [`of US restaurants didn't turn a profit last year <em>(National Restaurant Association)</em>.`, `अमेरिकी रेस्तराँ पिछले साल मुनाफ़ा नहीं कमा पाए <em>(National Restaurant Association)</em>।`, `امریکی ریستوران پچھلے سال منافع نہیں کما سکے <em>(National Restaurant Association)</em>۔`],
    [`what it costs to take an order on your own site — versus up to 30% the delivery apps keep.`, `अपनी साइट पर ऑर्डर लेने का खर्च — जबकि डिलीवरी ऐप्स 30% तक रख लेते हैं।`, `اپنی سائٹ پر آرڈر لینے کا خرچ — جبکہ ڈیلیوری ایپس 30% تک رکھ لیتے ہیں۔`],
    [`more revenue for an independent with each one-star rating bump <em>(Harvard Business School)</em>.`, `हर एक-स्टार रेटिंग बढ़ने पर एक आज़ाद रेस्तराँ की ज़्यादा कमाई <em>(Harvard Business School)</em>।`, `ہر ایک-اسٹار ریٹنگ بڑھنے پر ایک خود مختار ریستوران کی زیادہ آمدنی <em>(Harvard Business School)</em>۔`],
    [`only 28% of operators say tech ever improved their profit — we're built to be the exception <em>(National Restaurant Association)</em>.`, `सिर्फ़ 28% मालिक कहते हैं कि टेक से उनका मुनाफ़ा बढ़ा — हम अपवाद बनने के लिए बने हैं <em>(National Restaurant Association)</em>।`, `صرف 28% مالکان کہتے ہیں کہ ٹیک سے ان کا منافع بڑھا — ہم استثنا بننے کے لیے بنے ہیں <em>(National Restaurant Association)</em>۔`],

    // MID CTA
    [`See exactly where your restaurant is leaking — free, and yours to keep.`, `देखिए आपका रेस्तराँ कहाँ-कहाँ पैसा खो रहा है — मुफ़्त, और पूरी तरह आपका।`, `دیکھیے آپ کا ریستوران کہاں کہاں پیسہ کھو رہا ہے — مفت، اور پوری طرح آپ کا۔`],

    // HOW WE WORK
    [`One team, end to end — and we never really leave.`, `एक टीम, शुरू से आख़िर तक — और हम कभी सच में नहीं जाते।`, `ایک ٹیم، شروع سے آخر تک — اور ہم کبھی واقعی نہیں جاتے۔`],
    [`You get one person who knows your restaurant, and a full team behind them doing the work. We take you the whole way — from the first leak to the long run.`, `आपको एक व्यक्ति मिलता है जो आपके रेस्तराँ को समझता है, और उसके पीछे काम करती पूरी टीम। हम आपको पूरे रास्ते साथ ले चलते हैं — पहली कमी से लेकर लंबी दौड़ तक।`, `آپ کو ایک شخص ملتا ہے جو آپ کے ریستوران کو سمجھتا ہے، اور اس کے پیچھے کام کرتی پوری ٹیم۔ ہم آپ کو پورے راستے ساتھ لے چلتے ہیں — پہلی کمی سے لے کر لمبی دوڑ تک۔`],
    [`Find the leaks`, `कमियाँ खोजें`, `کمیاں تلاش کریں`],
    [`We dig into your numbers and show you exactly where money's slipping out — then hand you a plan with the cost and the expected return in plain dollars, before you spend a thing.`, `हम आपके आँकड़ों में गहराई से देखते हैं और बताते हैं कि पैसा कहाँ निकल रहा है — फिर खर्च और अनुमानित फ़ायदा साफ़ डॉलर में बताते हुए एक योजना देते हैं, इससे पहले कि आप कुछ खर्च करें।`, `ہم آپ کے اعداد و شمار میں گہرائی سے دیکھتے ہیں اور بتاتے ہیں کہ پیسہ کہاں نکل رہا ہے — پھر خرچ اور متوقع فائدہ صاف ڈالر میں بتاتے ہوئے ایک منصوبہ دیتے ہیں، اس سے پہلے کہ آپ کچھ خرچ کریں۔`],
    [`Stop the bleed, then grow`, `रिसाव रोकें, फिर बढ़ें`, `رساؤ روکیں، پھر بڑھیں`],
    [`We start with the fastest-payback fixes so the work pays for itself — then connect your systems and add the advantages the big chains have, as each one earns its place.`, `हम सबसे जल्दी फ़ायदा देने वाले सुधारों से शुरू करते हैं ताकि काम अपना खर्च खुद निकाल ले — फिर आपके सिस्टम जोड़ते हैं और बड़ी चेन वाली सुविधाएँ जोड़ते हैं, जैसे-जैसे हर एक अपनी जगह बनाए।`, `ہم سب سے جلدی فائدہ دینے والے کاموں سے شروع کرتے ہیں تاکہ کام اپنا خرچ خود نکال لے — پھر آپ کے سسٹم جوڑتے ہیں اور بڑی چین والی سہولتیں شامل کرتے ہیں، جیسے جیسے ہر ایک اپنی جگہ بنائے۔`],
    [`Stay as your team`, `आपकी टीम बनकर रहें`, `آپ کی ٹیم بن کر رہیں`],
    [`We don't hand off and disappear. We stay on as the tech team you could never hire on your own — because it never stops evolving, and neither do we.`, `हम काम सौंपकर ग़ायब नहीं होते। हम वही टेक टीम बनकर रहते हैं जिसे आप अकेले कभी रख नहीं सकते — क्योंकि तकनीक बदलती रहती है, और हम भी।`, `ہم کام سونپ کر غائب نہیں ہوتے۔ ہم وہی ٹیک ٹیم بن کر رہتے ہیں جسے آپ اکیلے کبھی رکھ نہیں سکتے — کیونکہ ٹیکنالوجی بدلتی رہتی ہے، اور ہم بھی۔`],
    [`Our goal isn't to sell you software and walk away. It's to be the team that keeps <strong>your restaurant winning</strong> — this year, and every year after.`, `हमारा मक़सद आपको सॉफ़्टवेयर बेचकर चले जाना नहीं है। हमारा मक़सद वह टीम बनना है जो <strong>आपके रेस्तराँ को जिताती रहे</strong> — इस साल, और हर आने वाले साल।`, `ہمارا مقصد آپ کو سافٹ ویئر بیچ کر چلے جانا نہیں ہے۔ ہمارا مقصد وہ ٹیم بننا ہے جو <strong>آپ کے ریستوران کو جِتاتی رہے</strong> — اس سال، اور ہر آنے والے سال۔`],

    // STORY
    [`Why us`, `हम ही क्यों`, `ہم ہی کیوں`],
    [`We've stood on your side of the line.`, `हम भी उसी तरफ़ खड़े रहे हैं जहाँ आप हैं।`, `ہم بھی اُسی طرف کھڑے رہے ہیں جہاں آپ ہیں۔`],
    [`We're a restaurant family first. <strong>Fifteen-plus years</strong> in hospitality across <strong>Canada and India</strong>, a restaurant of our own in Canada, and today <strong>Wok &amp; Karahi</strong> in Spring, Texas — recognized as the <strong>Best Halal Chinese Indo-Pak in Houston</strong>, and highly rated. We've lived the 12-hour days, the app fees, the no-shows, and the tools that fight you instead of helping.`, `हम सबसे पहले एक रेस्तराँ परिवार हैं। <strong>पंद्रह से ज़्यादा साल</strong> का हॉस्पिटैलिटी अनुभव <strong>कनाडा और भारत</strong> में, कनाडा में अपना एक रेस्तराँ, और आज स्प्रिंग, टेक्सस में <strong>Wok &amp; Karahi</strong> — <strong>ह्यूस्टन का बेस्ट हलाल चाइनीज़ इंडो-पाक</strong> माना गया, और बेहतरीन रेटिंग वाला। हमने भी 12-12 घंटे की मेहनत, ऐप की फ़ीस, न आने वाले ग्राहक, और मदद के बजाय अड़चन बनने वाले टूल झेले हैं।`, `ہم سب سے پہلے ایک ریستوران خاندان ہیں۔ <strong>پندرہ سے زیادہ سال</strong> کا ہاسپٹیلٹی تجربہ <strong>کینیڈا اور انڈیا</strong> میں، کینیڈا میں اپنا ایک ریستوران، اور آج اسپرنگ، ٹیکساس میں <strong>Wok &amp; Karahi</strong> — <strong>ہیوسٹن کا بہترین حلال چائنیز اِنڈو-پاک</strong> مانا گیا، اور اعلیٰ ریٹنگ والا۔ ہم نے بھی 12-12 گھنٹے کی محنت، ایپ کی فیس، نہ آنے والے گاہک، اور مدد کے بجائے رکاوٹ بننے والے ٹولز جھیلے ہیں۔`],
    [`Behind the scenes, we pair that with <strong>serious engineering muscle</strong> — led by our founder, a senior software architect who builds production-grade systems for global companies and works with the newest AI every day. So you get the seven-day-a-week reality of the floor <em>and</em> enterprise-grade capability, in one partner. You deal with one person who genuinely gets it; our team makes it all happen.`, `पर्दे के पीछे, हम इसके साथ जोड़ते हैं <strong>मज़बूत इंजीनियरिंग ताक़त</strong> — हमारे संस्थापक की अगुवाई में, जो एक सीनियर सॉफ़्टवेयर आर्किटेक्ट हैं और दुनिया भर की कंपनियों के लिए प्रोडक्शन-स्तर के सिस्टम बनाते हैं और हर दिन नई से नई AI के साथ काम करते हैं। तो आपको मिलती है फ़्लोर की सातों दिन की हक़ीक़त <em>और</em> एंटरप्राइज़-स्तर की क्षमता, एक ही पार्टनर में। आप एक ऐसे व्यक्ति से बात करते हैं जो सच में समझता है; बाक़ी सब हमारी टीम कर देती है।`, `پردے کے پیچھے، ہم اس کے ساتھ جوڑتے ہیں <strong>مضبوط انجینئرنگ طاقت</strong> — ہمارے بانی کی قیادت میں، جو ایک سینئر سافٹ ویئر آرکیٹیکٹ ہیں اور دنیا بھر کی کمپنیوں کے لیے پروڈکشن-سطح کے سسٹم بناتے ہیں اور ہر دن نئی سے نئی AI کے ساتھ کام کرتے ہیں۔ تو آپ کو ملتی ہے فلور کی ساتوں دن کی حقیقت <em>اور</em> انٹرپرائز-سطح کی صلاحیت، ایک ہی پارٹنر میں۔ آپ ایک ایسے شخص سے بات کرتے ہیں جو واقعی سمجھتا ہے؛ باقی سب ہماری ٹیم کر دیتی ہے۔`],
    [`<strong>A real result:</strong> we doubled a restaurant's online ratings and lifted its score — and for an independent, each star is worth roughly 5–9% in revenue. That's the kind of change we build, not just advise on.`, `<strong>एक असली नतीजा:</strong> हमने एक रेस्तराँ की ऑनलाइन रेटिंग्स की संख्या दोगुनी की और उसका स्कोर बढ़ाया — और एक आज़ाद रेस्तराँ के लिए, हर स्टार करीब 5–9% कमाई के बराबर है। हम ऐसा ही बदलाव बनाते हैं, सिर्फ़ सलाह नहीं देते।`, `<strong>ایک حقیقی نتیجہ:</strong> ہم نے ایک ریستوران کی آن لائن ریٹنگز کی تعداد دوگنی کی اور اس کا اسکور بڑھایا — اور ایک خود مختار ریستوران کے لیے، ہر اسٹار تقریباً 5–9% آمدنی کے برابر ہے۔ ہم ایسا ہی بدلاؤ بناتے ہیں، صرف مشورہ نہیں دیتے۔`],
    [`Abbas &amp; his father, Zoeb — at Wok &amp; Karahi, Spring, TX`, `अब्बास और उनके पिता, ज़ोएब — Wok &amp; Karahi, स्प्रिंग, TX में`, `عباس اور اُن کے والد، ذوئب — Wok &amp; Karahi، اسپرنگ، TX میں`],
    [`Your customers and your data stay yours. We give you the muscle the big chains have — and you keep the keys.`, `आपके ग्राहक और आपका डेटा आपके ही रहते हैं। हम आपको बड़ी चेन वाली ताक़त देते हैं — और चाबियाँ आपके पास रहती हैं।`, `آپ کے گاہک اور آپ کا ڈیٹا آپ ہی کے رہتے ہیں۔ ہم آپ کو بڑی چین والی طاقت دیتے ہیں — اور چابیاں آپ کے پاس رہتی ہیں۔`],
    [`— What AZ Restaurant Partners stands for`, `— AZ Restaurant Partners किसके लिए खड़ा है`, `— AZ Restaurant Partners کس کے لیے کھڑا ہے`],

    // STRATEGIES
    [`How we'd grow your restaurant`, `हम आपका रेस्तराँ कैसे बढ़ाएँगे`, `ہم آپ کا ریستوران کیسے بڑھائیں گے`],
    [`Use what works. Fix what leaks. Own what's yours.`, `जो काम करे उसे अपनाएँ। जो रिसे उसे ठीक करें। जो आपका है उस पर हक़ रखें।`, `جو کام کرے اسے اپنائیں۔ جو رِسے اسے ٹھیک کریں۔ جو آپ کا ہے اس پر حق رکھیں۔`],
    [`We don't fight the apps or rip out what's working — we use them smarter. Tell us what you run, and we'll show you exactly where we'd start:`, `हम ऐप्स से नहीं लड़ते और जो चल रहा है उसे नहीं उखाड़ते — हम उन्हें समझदारी से इस्तेमाल करते हैं। बताइए आप क्या चलाते हैं, और हम बताएँगे कि हम कहाँ से शुरू करेंगे:`, `ہم ایپس سے نہیں لڑتے اور جو چل رہا ہے اسے نہیں اکھاڑتے — ہم انہیں سمجھداری سے استعمال کرتے ہیں۔ بتائیے آپ کیا چلاتے ہیں، اور ہم بتائیں گے کہ ہم کہاں سے شروع کریں گے:`],
    [`Which sounds like you?`, `इनमें से आप कौन हैं?`, `ان میں سے آپ کون ہیں؟`],
    [`Takeout or counter`, `टेकआउट या काउंटर`, `ٹیک آؤٹ یا کاؤنٹر`],
    [`Sit-down restaurant`, `बैठकर खाने वाला रेस्तराँ`, `بیٹھ کر کھانے والا ریستوران`],
    [`2–10 locations`, `2–10 लोकेशन`, `2–10 مقامات`],
    // cards
    [`Treat the apps as discovery — then win the customer`, `ऐप्स को पहचान का ज़रिया मानें — फिर ग्राहक जीतें`, `ایپس کو پہچان کا ذریعہ مانیں — پھر گاہک جیتیں`],
    [`The apps are great at getting you <em>found</em>. The mistake is letting them keep the guest. We capture the customers they send you and turn them into direct, repeat orders on your own site — you keep the relationship and the margin. (Still want to deliver? White-label drivers, ~$8 flat.)`, `ऐप्स आपको <em>ढूँढवाने</em> में बढ़िया हैं। ग़लती है उन्हें ग्राहक रखने देना। हम उनके भेजे ग्राहकों को पकड़ते हैं और उन्हें आपकी अपनी साइट पर सीधे, बार-बार के ऑर्डर में बदलते हैं — रिश्ता और मुनाफ़ा आपके पास। (डिलीवरी भी करनी है? व्हाइट-लेबल ड्राइवर, करीब $8 फ़्लैट।)`, `ایپس آپ کو <em>ڈھونڈوانے</em> میں بہترین ہیں۔ غلطی ہے انہیں گاہک رکھنے دینا۔ ہم ان کے بھیجے گاہکوں کو پکڑتے ہیں اور انہیں آپ کی اپنی سائٹ پر براہِ راست، بار بار کے آرڈر میں بدلتے ہیں — رشتہ اور منافع آپ کے پاس۔ (ڈیلیوری بھی کرنی ہے؟ وائٹ-لیبل ڈرائیور، تقریباً $8 فلیٹ۔)`],
    [`Know your regulars — and bring them back`, `अपने नियमित ग्राहक जानें — और उन्हें वापस लाएँ`, `اپنے مستقل گاہک جانیں — اور انہیں واپس لائیں`],
    [`Right now the apps know your customers and you don't. We help you build your own guest list and quietly bring people back with the right nudge — not blanket discounts — so repeat visits grow on their own.`, `अभी ऐप्स आपके ग्राहकों को जानते हैं, आप नहीं। हम आपकी अपनी ग्राहक सूची बनाने में मदद करते हैं और सही याद-दहानी से लोगों को चुपचाप वापस लाते हैं — हर किसी को छूट देकर नहीं — ताकि बार-बार आने वाले ग्राहक खुद बढ़ें।`, `ابھی ایپس آپ کے گاہکوں کو جانتے ہیں، آپ نہیں۔ ہم آپ کی اپنی گاہک فہرست بنانے میں مدد کرتے ہیں اور صحیح یاد دہانی سے لوگوں کو خاموشی سے واپس لاتے ہیں — ہر کسی کو رعایت دے کر نہیں — تاکہ بار بار آنے والے گاہک خود بڑھیں۔`],
    [`Answer every call, around the clock`, `हर कॉल का जवाब, दिन-रात`, `ہر کال کا جواب، دن رات`],
    [`An AI voice agent takes orders and books tables 24/7, so no rush ever sends money to voicemail.`, `एक AI वॉइस एजेंट 24/7 ऑर्डर लेता है और टेबल बुक करता है, ताकि भीड़ के समय भी कोई पैसा वॉइसमेल में न जाए।`, `ایک AI وائس ایجنٹ 24/7 آرڈر لیتا ہے اور ٹیبل بُک کرتا ہے، تاکہ رش کے وقت بھی کوئی پیسہ وائس میل میں نہ جائے۔`],
    [`End the tablet chaos`, `टैबलेट की अफ़रा-तफ़री ख़त्म करें`, `ٹیبلٹ کی افراتفری ختم کریں`],
    [`All your delivery apps flowing into one screen and into your POS — instead of three tablets beeping at the counter and orders re-keyed by hand.`, `आपके सारे डिलीवरी ऐप्स एक ही स्क्रीन और आपके POS में आते हुए — काउंटर पर तीन टैबलेट बजने और हाथ से ऑर्डर दोबारा टाइप करने के बजाय।`, `آپ کے سارے ڈیلیوری ایپس ایک ہی اسکرین اور آپ کے POS میں آتے ہوئے — کاؤنٹر پر تین ٹیبلٹ بجنے اور ہاتھ سے آرڈر دوبارہ ٹائپ کرنے کے بجائے۔`],
    [`More 5-star reviews — the smart way`, `ज़्यादा 5-स्टार रिव्यू — समझदारी से`, `زیادہ 5-اسٹار ریویوز — سمجھداری سے`],
    [`We nudge happy guests to post publicly and catch unhappy ones privately before they do — so your rating climbs steadily and every review gets answered on time. For an independent, each star is worth roughly 5–9% in revenue.`, `हम ख़ुश ग्राहकों को सार्वजनिक रिव्यू के लिए प्रेरित करते हैं और नाख़ुश ग्राहकों को पहले ही निजी तौर पर पकड़ लेते हैं — ताकि आपकी रेटिंग लगातार बढ़े और हर रिव्यू का समय पर जवाब हो। एक आज़ाद रेस्तराँ के लिए, हर स्टार करीब 5–9% कमाई के बराबर है।`, `ہم خوش گاہکوں کو عوامی ریویو کے لیے ابھارتے ہیں اور ناخوش گاہکوں کو پہلے ہی نجی طور پر پکڑ لیتے ہیں — تاکہ آپ کی ریٹنگ مسلسل بڑھے اور ہر ریویو کا بروقت جواب ہو۔ ایک خود مختار ریستوران کے لیے، ہر اسٹار تقریباً 5–9% آمدنی کے برابر ہے۔`],
    [`Get found by AI, not just Google`, `सिर्फ़ Google नहीं, AI पर भी मिलें`, `صرف Google نہیں، AI پر بھی ملیں`],
    [`Make your menu and hours readable to ChatGPT, Gemini, and Maps, so you're the place they recommend — and the orders follow.`, `अपना मेन्यू और समय ChatGPT, Gemini और Maps के पढ़ने लायक बनाएँ, ताकि वे आपको ही सुझाएँ — और ऑर्डर पीछे-पीछे आएँ।`, `اپنا مینو اور اوقات ChatGPT، Gemini اور Maps کے پڑھنے لائق بنائیں، تاکہ وہ آپ ہی کو تجویز کریں — اور آرڈر پیچھے پیچھے آئیں۔`],
    [`Catering &amp; corporate lunches, done right`, `कैटरिंग और कॉर्पोरेट लंच, सही तरीक़े से`, `کیٹرنگ اور کارپوریٹ لنچ، صحیح طریقے سے`],
    [`A real catering channel — bigger orders, recurring office lunches, white-label delivery — at margins far above your dine-in.`, `एक असली कैटरिंग चैनल — बड़े ऑर्डर, नियमित ऑफ़िस लंच, व्हाइट-लेबल डिलीवरी — आपके डाइन-इन से कहीं ज़्यादा मुनाफ़े पर।`, `ایک حقیقی کیٹرنگ چینل — بڑے آرڈر، باقاعدہ آفس لنچ، وائٹ-لیبل ڈیلیوری — آپ کے ڈائن-اِن سے کہیں زیادہ منافع پر۔`],
    [`Recover what the apps owe you`, `जो ऐप्स पर बकाया है वह वसूलें`, `جو ایپس پر واجب ہے وہ وصول کریں`],
    [`The apps quietly short you — wrong charges, bogus refunds, missed payouts. We audit them and claw back the money that's actually yours, then keep watching so it doesn't pile up again.`, `ऐप्स चुपचाप आपका हक़ मारते हैं — ग़लत चार्ज, झूठे रिफ़ंड, छूटे भुगतान। हम उनकी जाँच करते हैं और वह पैसा वापस खींचते हैं जो असल में आपका है, फिर नज़र रखते हैं ताकि दोबारा न जमा हो।`, `ایپس خاموشی سے آپ کا حق مارتے ہیں — غلط چارجز، جھوٹے ریفنڈ، چھوٹی ادائیگیاں۔ ہم ان کا آڈٹ کرتے ہیں اور وہ پیسہ واپس کھینچتے ہیں جو اصل میں آپ کا ہے، پھر نظر رکھتے ہیں تاکہ دوبارہ جمع نہ ہو۔`],
    // fit lines
    [`<span class="yes">Fit if</span> the apps bring orders but you never see the customer again.`, `<span class="yes">सही अगर</span> ऐप्स ऑर्डर तो लाते हैं पर ग्राहक दोबारा कभी नहीं दिखता।`, `<span class="yes">صحیح اگر</span> ایپس آرڈر تو لاتے ہیں مگر گاہک دوبارہ کبھی نہیں دکھتا۔`],
    [`<span class="no">Maybe not</span> if you do little delivery or takeout.`, `<span class="no">शायद नहीं</span> अगर आप बहुत कम डिलीवरी या टेकआउट करते हैं।`, `<span class="no">شاید نہیں</span> اگر آپ بہت کم ڈیلیوری یا ٹیک آؤٹ کرتے ہیں۔`],
    [`<span class="yes">Fit if</span> you couldn't email your top 20 regulars today.`, `<span class="yes">सही अगर</span> आप आज अपने टॉप 20 नियमित ग्राहकों को ईमेल नहीं कर सकते।`, `<span class="yes">صحیح اگر</span> آپ آج اپنے ٹاپ 20 مستقل گاہکوں کو ای میل نہیں کر سکتے۔`],
    [`<span class="no">Maybe not</span> if you already run a healthy first-party list.`, `<span class="no">शायद नहीं</span> अगर आपके पास पहले से अच्छी ग्राहक सूची है।`, `<span class="no">شاید نہیں</span> اگر آپ کے پاس پہلے سے اچھی گاہک فہرست ہے۔`],
    [`<span class="yes">Fit if</span> you lose takeout or reservation calls during peaks.`, `<span class="yes">सही अगर</span> भीड़ के समय आपके टेकआउट या रिज़र्वेशन कॉल छूट जाते हैं।`, `<span class="yes">صحیح اگر</span> رش کے وقت آپ کے ٹیک آؤٹ یا ریزرویشن کالز چھوٹ جاتے ہیں۔`],
    [`<span class="no">Maybe not</span> if your call volume is genuinely low.`, `<span class="no">शायद नहीं</span> अगर आपके यहाँ कॉल वाक़ई बहुत कम आते हैं।`, `<span class="no">شاید نہیں</span> اگر آپ کے یہاں کالز واقعی بہت کم آتے ہیں۔`],
    [`<span class="yes">Fit if</span> you're juggling DoorDash, Uber &amp; Grubhub tablets.`, `<span class="yes">सही अगर</span> आप DoorDash, Uber और Grubhub के टैबलेट संभाल रहे हैं।`, `<span class="yes">صحیح اگر</span> آپ DoorDash، Uber اور Grubhub کے ٹیبلٹ سنبھال رہے ہیں۔`],
    [`<span class="no">Maybe not</span> if the apps already feed your POS.`, `<span class="no">शायद नहीं</span> अगर ऐप्स पहले से आपके POS में आते हैं।`, `<span class="no">شاید نہیں</span> اگر ایپس پہلے سے آپ کے POS میں آتے ہیں۔`],
    [`<span class="yes">Fit if</span> your rating is stuck or slipping.`, `<span class="yes">सही अगर</span> आपकी रेटिंग अटकी है या गिर रही है।`, `<span class="yes">صحیح اگر</span> آپ کی ریٹنگ اٹکی ہے یا گر رہی ہے۔`],
    [`<span class="no">Maybe not</span> as a top priority for big chains.`, `<span class="no">शायद नहीं</span> बड़ी चेन के लिए सबसे पहली प्राथमिकता के तौर पर।`, `<span class="no">شاید نہیں</span> بڑی چین کے لیے سب سے پہلی ترجیح کے طور پر۔`],
    [`<span class="yes">Fit if</span> people search "best [your food] near me."`, `<span class="yes">सही अगर</span> लोग "best [आपका खाना] near me" सर्च करते हैं।`, `<span class="yes">صحیح اگر</span> لوگ "best [آپ کا کھانا] near me" سرچ کرتے ہیں۔`],
    [`<span class="no">Maybe not</span> if you're purely a regulars-only neighborhood spot.`, `<span class="no">शायद नहीं</span> अगर आप सिर्फ़ मोहल्ले के नियमित ग्राहकों वाली जगह हैं।`, `<span class="no">شاید نہیں</span> اگر آپ صرف محلے کے مستقل گاہکوں والی جگہ ہیں۔`],
    [`<span class="yes">Fit if</span> you've got kitchen capacity and local offices nearby.`, `<span class="yes">सही अगर</span> आपके पास किचन की गुंजाइश है और आस-पास ऑफ़िस हैं।`, `<span class="yes">صحیح اگر</span> آپ کے پاس کچن کی گنجائش ہے اور آس پاس آفس ہیں۔`],
    [`<span class="no">Maybe not</span> if you're already at full capacity at peak.`, `<span class="no">शायद नहीं</span> अगर आप भीड़ के समय पहले से पूरी क्षमता पर हैं।`, `<span class="no">شاید نہیں</span> اگر آپ رش کے وقت پہلے سے پوری گنجائش پر ہیں۔`],
    [`<span class="yes">Fit if</span> you run real delivery volume across the apps.`, `<span class="yes">सही अगर</span> आप ऐप्स पर अच्छी-ख़ासी डिलीवरी करते हैं।`, `<span class="yes">صحیح اگر</span> آپ ایپس پر خاصی ڈیلیوری کرتے ہیں۔`],
    [`<span class="no">Maybe not</span> if delivery is a tiny part of your business.`, `<span class="no">शायद नहीं</span> अगर डिलीवरी आपके कारोबार का बहुत छोटा हिस्सा है।`, `<span class="no">شاید نہیں</span> اگر ڈیلیوری آپ کے کاروبار کا بہت چھوٹا حصہ ہے۔`],
    [`See all plays`, `सभी तरीक़े देखें`, `تمام طریقے دیکھیں`],
    [`These are the high-impact plays — but there are <strong>100+ tools</strong> out there, and most owners don't know which (if any) fit them. <a href="#finder">See what fits your restaurant →</a>`, `ये सबसे असरदार तरीक़े हैं — पर बाहर <strong>100+ टूल्स</strong> मौजूद हैं, और ज़्यादातर मालिकों को पता ही नहीं कि कौन-सा (अगर कोई) उन पर सही बैठता है। <a href="#finder">देखें आपके रेस्तराँ पर क्या सही बैठता है →</a>`, `یہ سب سے مؤثر طریقے ہیں — مگر باہر <strong>100+ ٹولز</strong> موجود ہیں، اور زیادہ تر مالکان کو پتا ہی نہیں کہ کون سا (اگر کوئی) ان پر صحیح بیٹھتا ہے۔ <a href="#finder">دیکھیں آپ کے ریستوران پر کیا صحیح بیٹھتا ہے →</a>`],

    // FINDER
    [`What's out there — and what fits you`, `बाहर क्या-क्या है — और आप पर क्या सही बैठता है`, `باہر کیا کیا ہے — اور آپ پر کیا صحیح بیٹھتا ہے`],
    [`There's a tool for everything. You only need the right few.`, `हर चीज़ के लिए एक टूल है। आपको बस सही चंद चाहिए।`, `ہر چیز کے لیے ایک ٹول ہے۔ آپ کو بس صحیح چند چاہئیں۔`],
    [`We track <strong>100+ restaurant tools across 22 categories</strong> — and most owners have never heard of the handful that would actually move their numbers. Tap the <span class="finder__hintword">highlighted words</span> to describe your place, and we'll show you what likely fits, what it tends to cost, and what to skip — then send the full breakdown and set up your free call.`, `हम <strong>22 श्रेणियों में 100+ रेस्तराँ टूल्स</strong> पर नज़र रखते हैं — और ज़्यादातर मालिकों ने उन चंद टूल्स का नाम तक नहीं सुना जो वाक़ई उनके आँकड़े बदल देंगे। अपनी जगह बताने के लिए <span class="finder__hintword">हाइलाइट किए शब्दों</span> पर टैप करें, और हम बताएँगे कि क्या सही बैठेगा, उसका आम तौर पर क्या खर्च होता है, और क्या छोड़ देना है — फिर पूरा ब्यौरा भेजेंगे और आपकी मुफ़्त कॉल तय करेंगे।`, `ہم <strong>22 زمروں میں 100+ ریستوران ٹولز</strong> پر نظر رکھتے ہیں — اور زیادہ تر مالکان نے ان چند ٹولز کا نام تک نہیں سنا جو واقعی ان کے اعداد بدل دیں گے۔ اپنی جگہ بتانے کے لیے <span class="finder__hintword">نمایاں کیے گئے الفاظ</span> پر ٹیپ کریں، اور ہم بتائیں گے کہ کیا صحیح بیٹھے گا، اس کا عام طور پر کیا خرچ ہوتا ہے، اور کیا چھوڑ دینا ہے — پھر پورا تفصیلی خاکہ بھیجیں گے اور آپ کی مفت کال طے کریں گے۔`],

    // FAQ
    [`Good questions`, `अच्छे सवाल`, `اچھے سوالات`],
    [`What owners ask us first.`, `मालिक हमसे सबसे पहले क्या पूछते हैं।`, `مالکان ہم سے سب سے پہلے کیا پوچھتے ہیں۔`],
    [`Is this just one person?`, `क्या यह सिर्फ़ एक आदमी है?`, `کیا یہ صرف ایک آدمی ہے؟`],
    [`No. You get <em>one</em> point of contact who knows your restaurant — and a full team behind them building, integrating, testing, and running everything to a production-grade standard. One relationship, real horsepower.`, `नहीं। आपको <em>एक</em> संपर्क व्यक्ति मिलता है जो आपके रेस्तराँ को जानता है — और उसके पीछे पूरी टीम जो सब कुछ बनाती, जोड़ती, जाँचती और प्रोडक्शन-स्तर पर चलाती है। एक रिश्ता, असली ताक़त।`, `نہیں۔ آپ کو <em>ایک</em> رابطہ شخص ملتا ہے جو آپ کے ریستوران کو جانتا ہے — اور اس کے پیچھے پوری ٹیم جو سب کچھ بناتی، جوڑتی، جانچتی اور پروڈکشن-سطح پر چلاتی ہے۔ ایک رشتہ، حقیقی طاقت۔`],
    [`What happens on the free call?`, `मुफ़्त कॉल पर क्या होता है?`, `مفت کال پر کیا ہوتا ہے؟`],
    [`We talk through your restaurant — where it's winning and where it's leaking money — and point you to the highest-impact move, whether or not we end up working together. No slides, no pressure.`, `हम आपके रेस्तराँ पर बात करते हैं — कहाँ अच्छा चल रहा है और कहाँ पैसा रिस रहा है — और सबसे असरदार क़दम बताते हैं, चाहे हम साथ काम करें या नहीं। न स्लाइड्स, न दबाव।`, `ہم آپ کے ریستوران پر بات کرتے ہیں — کہاں اچھا چل رہا ہے اور کہاں پیسہ رِس رہا ہے — اور سب سے مؤثر قدم بتاتے ہیں، چاہے ہم ساتھ کام کریں یا نہیں۔ نہ سلائیڈز، نہ دباؤ۔`],
    [`Do you disappear after it's built?`, `बनाने के बाद क्या आप ग़ायब हो जाते हैं?`, `بنانے کے بعد کیا آپ غائب ہو جاتے ہیں؟`],
    [`Never. We don't do drop-and-leave. We stay on — automated monitoring plus real check-ins — because the tools and the market keep evolving, and so should your restaurant. That long-term partnership is the whole point.`, `कभी नहीं। हम बनाकर छोड़ने वाले नहीं हैं। हम साथ रहते हैं — ऑटोमेटेड निगरानी और असली बातचीत — क्योंकि टूल और बाज़ार बदलते रहते हैं, और आपके रेस्तराँ को भी बदलना चाहिए। यही लंबी साझेदारी असल मक़सद है।`, `کبھی نہیں۔ ہم بنا کر چھوڑنے والے نہیں ہیں۔ ہم ساتھ رہتے ہیں — خودکار نگرانی اور حقیقی رابطے — کیونکہ ٹولز اور مارکیٹ بدلتے رہتے ہیں، اور آپ کے ریستوران کو بھی بدلنا چاہیے۔ یہی طویل شراکت اصل مقصد ہے۔`],
    [`Can't I just do this myself?`, `क्या मैं यह ख़ुद नहीं कर सकता?`, `کیا میں یہ خود نہیں کر سکتا؟`],
    [`You can — and the finder above points you straight to the tools. But choosing among dozens of options, wiring them into your POS, and proving the ROI is the hard, time-consuming part. That's exactly what we do, end to end — so you get the result without the risk.`, `कर सकते हैं — और ऊपर का फ़ाइंडर आपको सीधे टूल्स तक ले जाता है। पर दर्जनों विकल्पों में से चुनना, उन्हें अपने POS से जोड़ना, और ROI साबित करना — यही मुश्किल और समय खाने वाला हिस्सा है। हम बिल्कुल यही करते हैं, शुरू से आख़िर तक — ताकि नतीजा मिले, जोखिम के बिना।`, `کر سکتے ہیں — اور اوپر کا فائنڈر آپ کو سیدھے ٹولز تک لے جاتا ہے۔ مگر درجنوں اختیارات میں سے چننا، انہیں اپنے POS سے جوڑنا، اور ROI ثابت کرنا — یہی مشکل اور وقت کھانے والا حصہ ہے۔ ہم بالکل یہی کرتے ہیں، شروع سے آخر تک — تاکہ نتیجہ ملے، خطرے کے بغیر۔`],

    // WHAT IT COSTS
    [`What it costs`, `इसका खर्च`, `اس کا خرچ`],
    [`No leap of faith. You see the numbers first.`, `कोई अंधा भरोसा नहीं। पहले आँकड़े देखिए।`, `کوئی اندھا بھروسا نہیں۔ پہلے اعداد دیکھیے۔`],
    [`Whether you need a one-time fix or an ongoing team, we scope it to your restaurant — and you never spend a dollar on faith.`, `चाहे आपको एक बार का सुधार चाहिए या लगातार साथ देने वाली टीम, हम इसे आपके रेस्तराँ के हिसाब से तय करते हैं — और आप कभी भरोसे के भरोसे एक डॉलर भी खर्च नहीं करते।`, `چاہے آپ کو ایک بار کا حل چاہیے یا مسلسل ساتھ دینے والی ٹیم، ہم اسے آپ کے ریستوران کے مطابق طے کرتے ہیں — اور آپ کبھی صرف بھروسے پر ایک ڈالر بھی خرچ نہیں کرتے۔`],
    [`You see the numbers first`, `पहले आँकड़े आपके सामने`, `پہلے اعداد آپ کے سامنے`],
    [`Before anything starts, you get the plan, the cost, and the expected return in plain dollars. If the math doesn't work for you, we don't move.`, `कुछ भी शुरू होने से पहले, आपको योजना, खर्च और अनुमानित फ़ायदा साफ़ डॉलर में मिलता है। अगर हिसाब आपके लिए सही नहीं बैठता, तो हम आगे नहीं बढ़ते।`, `کچھ بھی شروع ہونے سے پہلے، آپ کو منصوبہ، خرچ اور متوقع فائدہ صاف ڈالر میں ملتا ہے۔ اگر حساب آپ کے لیے صحیح نہیں بیٹھتا، تو ہم آگے نہیں بڑھتے۔`],
    [`Built to pay for itself`, `अपना खर्च खुद निकाले`, `اپنا خرچ خود نکالے`],
    [`We start with the fastest-payback fixes — the ones that put money back this month — so the work funds everything that comes after it.`, `हम सबसे जल्दी फ़ायदा देने वाले सुधारों से शुरू करते हैं — जो इसी महीने पैसा वापस लाएँ — ताकि वही काम आगे की हर चीज़ का खर्च निकाल दे।`, `ہم سب سے جلدی فائدہ دینے والے کاموں سے شروع کرتے ہیں — جو اسی مہینے پیسہ واپس لائیں — تاکہ وہی کام آگے کی ہر چیز کا خرچ نکال دے۔`],
    [`No lock-in, ever`, `कभी कोई बंधन नहीं`, `کبھی کوئی پابندی نہیں`],
    [`Month to month. No long contracts, no bricked hardware, no surprise fees. You keep your guests, your data, and your tools — and can walk anytime.`, `महीने-दर-महीने। न लंबे कॉन्ट्रैक्ट, न बेकार हुआ हार्डवेयर, न चौंकाने वाली फ़ीस। आपके ग्राहक, आपका डेटा और आपके टूल आपके पास रहते हैं — और आप कभी भी जा सकते हैं।`, `مہینہ بہ مہینہ۔ نہ لمبے کنٹریکٹ، نہ بیکار ہوا ہارڈویئر، نہ چونکانے والی فیس۔ آپ کے گاہک، آپ کا ڈیٹا اور آپ کے ٹولز آپ کے پاس رہتے ہیں — اور آپ کبھی بھی جا سکتے ہیں۔`],
    [`Founding 5 · performance-first pilot`, `Founding 5 · नतीजे-पहले पायलट`, `Founding 5 · نتیجہ-اول پائلٹ`],
    [`We make you money before we take a dollar.`, `हम पहले आपको कमाई दिलाते हैं, फिर एक डॉलर लेते हैं।`, `ہم پہلے آپ کو کمائی دلاتے ہیں، پھر ایک ڈالر لیتے ہیں۔`],
    [`We're hand-picking <strong>five founding restaurants</strong>. For them, we put real money back in your pocket <em>first</em> — if we don't, you pay nothing. In return you get <strong>founding pricing locked for life</strong>, a direct line to the founder, and first access to everything we build. We only win when you do.`, `हम <strong>पाँच फ़ाउंडिंग रेस्तराँ</strong> ख़ुद चुन रहे हैं। उनके लिए, हम <em>पहले</em> आपकी जेब में असली पैसा डालते हैं — अगर नहीं डाल पाए, तो आप कुछ नहीं देते। बदले में आपको मिलता है <strong>फ़ाउंडिंग कीमत, हमेशा के लिए तय</strong>, संस्थापक से सीधी बात, और हमारी हर नई चीज़ तक पहली पहुँच। हम तभी जीतते हैं जब आप जीतते हैं।`, `ہم <strong>پانچ فاؤنڈنگ ریستوران</strong> خود چن رہے ہیں۔ ان کے لیے، ہم <em>پہلے</em> آپ کی جیب میں اصل پیسہ ڈالتے ہیں — اگر نہ ڈال سکے، تو آپ کچھ نہیں دیتے۔ بدلے میں آپ کو ملتا ہے <strong>فاؤنڈنگ قیمت، ہمیشہ کے لیے طے</strong>، بانی سے سیدھی بات، اور ہماری ہر نئی چیز تک پہلی رسائی۔ ہم تبھی جیتتے ہیں جب آپ جیتتے ہیں۔`],
    [`Apply to be one of the 5`, `इन 5 में शामिल होने के लिए आवेदन करें`, `ان 5 میں شامل ہونے کے لیے درخواست دیں`],
    [`Not ready to apply? The first call is still free — and you'll leave with at least one concrete way to keep more of what you earn. <a href="#contact">Book it here →</a>`, `अभी आवेदन के लिए तैयार नहीं? पहली कॉल फिर भी मुफ़्त है — और आप कम से कम एक ठोस तरीक़ा लेकर जाएँगे जिससे आप अपनी कमाई ज़्यादा बचा सकें। <a href="#contact">यहाँ बुक करें →</a>`, `ابھی درخواست کے لیے تیار نہیں؟ پہلی کال پھر بھی مفت ہے — اور آپ کم از کم ایک ٹھوس طریقہ لے کر جائیں گے جس سے آپ اپنی کمائی زیادہ بچا سکیں۔ <a href="#contact">یہاں بُک کریں →</a>`],

    // CONTACT
    [`Let's find the money your restaurant is leaving on the table.`, `आइए वह पैसा खोजें जो आपका रेस्तराँ यूँ ही छोड़ रहा है।`, `آئیے وہ پیسہ تلاش کریں جو آپ کا ریستوران یونہی چھوڑ رہا ہے۔`],
    [`Tell us a little about your place. We'll personally reply to set up a short video call — and you'll leave with at least one concrete way to keep more of what you earn. Free, no obligation.`, `अपनी जगह के बारे में थोड़ा बताइए। हम ख़ुद जवाब देकर एक छोटी वीडियो कॉल तय करेंगे — और आप कम से कम एक ठोस तरीक़ा लेकर जाएँगे जिससे आप अपनी कमाई ज़्यादा बचा सकें। मुफ़्त, बिना किसी बाध्यता के।`, `اپنی جگہ کے بارے میں تھوڑا بتائیے۔ ہم خود جواب دے کر ایک مختصر ویڈیو کال طے کریں گے — اور آپ کم از کم ایک ٹھوس طریقہ لے کر جائیں گے جس سے آپ اپنی کمائی زیادہ بچا سکیں۔ مفت، بغیر کسی پابندی کے۔`],
    [`Email`, `ईमेल`, `ای میل`],
    [`Phone`, `फ़ोन`, `فون`],
    [`Based in`, `स्थित`, `مقام`],
    [`Name`, `नाम`, `نام`],
    [`Restaurant`, `रेस्तराँ`, `ریستوران`],
    [`Phone <span class="opt">(optional)</span>`, `फ़ोन <span class="opt">(वैकल्पिक)</span>`, `فون <span class="opt">(اختیاری)</span>`],
    [`What would you like to change?`, `आप क्या बदलना चाहेंगे?`, `آپ کیا بدلنا چاہیں گے؟`],
    [`Request my free call`, `मेरी मुफ़्त कॉल का अनुरोध करें`, `میری مفت کال کی درخواست کریں`],
    [`Free &amp; no obligation. We read every message personally.`, `मुफ़्त और बिना किसी बाध्यता के। हम हर संदेश ख़ुद पढ़ते हैं।`, `مفت اور بغیر کسی پابندی کے۔ ہم ہر پیغام خود پڑھتے ہیں۔`],
    [`Your details are used only to reply to you — never shared or sold.`, `आपकी जानकारी सिर्फ़ आपको जवाब देने के लिए इस्तेमाल होती है — कभी साझा या बेची नहीं जाती।`, `آپ کی تفصیلات صرف آپ کو جواب دینے کے لیے استعمال ہوتی ہیں — کبھی شیئر یا فروخت نہیں کی جاتیں۔`],

    // FOOTER
    [`<strong>Keep more of what you earn.</strong> For independent, family-run restaurants — a restaurant family + an engineering team · Spring &amp; Greater Houston, TX.`, `<strong>अपनी कमाई ज़्यादा अपने पास रखें।</strong> आज़ाद, परिवार-संचालित रेस्तराँ के लिए — एक रेस्तराँ परिवार + एक इंजीनियरिंग टीम · स्प्रिंग और ग्रेटर ह्यूस्टन, TX।`, `<strong>اپنی کمائی زیادہ اپنے پاس رکھیں۔</strong> خود مختار، خاندانی ریستوران کے لیے — ایک ریستوران خاندان + ایک انجینئرنگ ٹیم · اسپرنگ اور گریٹر ہیوسٹن، TX۔`],
    // --- refreshed: PROBLEM band ---
    [`The real problem isn't just the apps.`, `असली समस्या सिर्फ़ ऐप्स नहीं हैं।`, `اصل مسئلہ صرف ایپس نہیں ہیں۔`],
    [`Big chains have whole teams for technology and strategy. You've got a kitchen to run — so money leaks where you don't have the time or the know-how to look:`, `बड़ी चेन के पास टेक्नोलॉजी और रणनीति के लिए पूरी टीमें होती हैं। आपके पास तो एक किचन चलाना है — इसलिए पैसा वहाँ रिसता है जहाँ देखने का न आपके पास समय है, न जानकारी:`, `بڑی چینز کے پاس ٹیکنالوجی اور حکمتِ عملی کے لیے پوری ٹیمیں ہوتی ہیں۔ آپ کے پاس تو ایک کچن چلانا ہے — اس لیے پیسہ وہاں رِستا ہے جہاں دیکھنے کا نہ آپ کے پاس وقت ہے، نہ معلومات:`],
    [`The apps keep <strong>15–30%</strong> of every order — and walk off with <strong>your customer</strong>.`, `ऐप्स हर ऑर्डर का <strong>15–30%</strong> रख लेते हैं — और <strong>आपका ग्राहक</strong> भी ले जाते हैं।`, `ایپس ہر آرڈر کا <strong>15–30%</strong> رکھ لیتے ہیں — اور <strong>آپ کا گاہک</strong> بھی لے جاتے ہیں۔`],
    [`The phone rings through the rush with <strong>no one free to answer it</strong>.`, `भीड़ के समय फ़ोन बजता रहता है पर <strong>उठाने वाला कोई फ़्री नहीं</strong>।`, `رش کے وقت فون بجتا رہتا ہے مگر <strong>اٹھانے والا کوئی فارغ نہیں</strong>۔`],
    [`A dozen tools that <strong>don't talk to each other</strong> — and no time to fix it.`, `दर्जनों टूल जो <strong>आपस में बात नहीं करते</strong> — और ठीक करने का समय नहीं।`, `درجنوں ٹولز جو <strong>آپس میں بات نہیں کرتے</strong> — اور ٹھیک کرنے کا وقت نہیں۔`],
    [`No clear view of your numbers, and <strong>no strategy</strong> the way the big chains have one.`, `अपने आँकड़ों की कोई साफ़ तस्वीर नहीं, और <strong>कोई रणनीति नहीं</strong> जैसी बड़ी चेन के पास होती है।`, `اپنے اعداد کی کوئی صاف تصویر نہیں، اور <strong>کوئی حکمتِ عملی نہیں</strong> جیسی بڑی چینز کے پاس ہوتی ہے۔`],
    [`<em>None of it is permanent — and you shouldn't have to become a tech expert to fix it.</em> That's our job: we bring the know-how, the industry strategy, and the team big chains pay for — and from the <strong>100+ tools out there</strong>, only the few that actually fit you. You keep control, your data, and the upside.`, `<em>यह सब हमेशा के लिए नहीं है — और इसे ठीक करने के लिए आपको टेक एक्सपर्ट बनने की ज़रूरत नहीं।</em> यह हमारा काम है: हम वह जानकारी, इंडस्ट्री की रणनीति और टीम लाते हैं जिसके लिए बड़ी चेन पैसे देती हैं — और <strong>बाहर मौजूद 100+ टूल्स में से</strong> सिर्फ़ वही चंद जो आप पर सही बैठें। नियंत्रण, आपका डेटा और फ़ायदा — सब आपके पास रहता है।`, `<em>یہ سب ہمیشہ کے لیے نہیں ہے — اور اسے ٹھیک کرنے کے لیے آپ کو ٹیک ماہر بننے کی ضرورت نہیں۔</em> یہ ہمارا کام ہے: ہم وہ معلومات، انڈسٹری کی حکمتِ عملی اور ٹیم لاتے ہیں جس کے لیے بڑی چینز پیسے دیتی ہیں — اور <strong>باہر موجود 100+ ٹولز میں سے</strong> صرف وہی چند جو آپ پر صحیح بیٹھیں۔ کنٹرول، آپ کا ڈیٹا اور فائدہ — سب آپ کے پاس رہتا ہے۔`],

    // --- refreshed: HOW IT WORKS ---
    [`How it works`, `यह कैसे काम करता है`, `یہ کیسے کام کرتا ہے`],
    [`You shouldn't need tech skills to run a modern restaurant.`, `आधुनिक रेस्तराँ चलाने के लिए आपको टेक स्किल्स की ज़रूरत नहीं होनी चाहिए।`, `جدید ریستوران چلانے کے لیے آپ کو ٹیک مہارت کی ضرورت نہیں ہونی چاہیے۔`],
    [`Our philosophy is simple: the big chains win with technology and strategy you don't have time to learn. We bring it — the know-how, the industry playbook, and the team — and put it to work for you. You stay in control, you own your data, and we only get paid when you win. Here's exactly how it goes — tap any step:`, `हमारा फ़लसफ़ा सीधा है: बड़ी चेन उस टेक्नोलॉजी और रणनीति से जीतती हैं जिसे सीखने का आपके पास समय नहीं। हम वह लाते हैं — जानकारी, इंडस्ट्री का तरीक़ा, और टीम — और उसे आपके लिए काम पर लगाते हैं। नियंत्रण आपके पास, डेटा आपका, और पैसे हम तभी लेते हैं जब आप जीतें। देखिए यह कैसे होता है — किसी भी क़दम पर टैप करें:`, `ہمارا فلسفہ سیدھا ہے: بڑی چینز اُس ٹیکنالوجی اور حکمتِ عملی سے جیتتی ہیں جسے سیکھنے کا آپ کے پاس وقت نہیں۔ ہم وہ لاتے ہیں — معلومات، انڈسٹری کا طریقہ، اور ٹیم — اور اسے آپ کے لیے کام پر لگاتے ہیں۔ کنٹرول آپ کے پاس، ڈیٹا آپ کا، اور پیسے ہم تبھی لیتے ہیں جب آپ جیتیں۔ دیکھیے یہ کیسے ہوتا ہے — کسی بھی قدم پر ٹیپ کریں:`],
    [`<span class="steps__n">1</span> You book a free call — we listen first`, `<span class="steps__n">1</span> आप एक मुफ़्त कॉल बुक करते हैं — हम पहले सुनते हैं`, `<span class="steps__n">1</span> آپ ایک مفت کال بُک کرتے ہیں — ہم پہلے سنتے ہیں`],
    [`<span class="steps__n">2</span> If it's a fit, we come to you`, `<span class="steps__n">2</span> अगर मेल बैठा, तो हम आपके पास आते हैं`, `<span class="steps__n">2</span> اگر میل بیٹھا، تو ہم آپ کے پاس آتے ہیں`],
    [`<span class="steps__n">3</span> We hand you a clear plan — work and cost`, `<span class="steps__n">3</span> हम आपको एक साफ़ योजना देते हैं — काम और खर्च`, `<span class="steps__n">3</span> ہم آپ کو ایک صاف منصوبہ دیتے ہیں — کام اور خرچ`],
    [`<span class="steps__n">4</span> You start saving — then we get paid`, `<span class="steps__n">4</span> आप बचत शुरू करते हैं — फिर हमें पैसे मिलते हैं`, `<span class="steps__n">4</span> آپ بچت شروع کرتے ہیں — پھر ہمیں پیسے ملتے ہیں`],
    [`<span class="steps__n">5</span> We prove it in your real numbers`, `<span class="steps__n">5</span> हम इसे आपके असली आँकड़ों में साबित करते हैं`, `<span class="steps__n">5</span> ہم اسے آپ کے اصل اعداد میں ثابت کرتے ہیں`],
    [`We get to know your restaurant and check that we're a fit. We'll show you the kinds of things we do for places like yours — but we won't prescribe anything until we've actually studied <em>your</em> business.`, `हम आपके रेस्तराँ को समझते हैं और देखते हैं कि मेल बैठता है या नहीं। हम आपको दिखाएँगे कि आप जैसी जगहों के लिए हम किस तरह के काम करते हैं — पर जब तक हम <em>आपके</em> कारोबार को सचमुच न समझ लें, कुछ तय नहीं करेंगे।`, `ہم آپ کے ریستوران کو سمجھتے ہیں اور دیکھتے ہیں کہ میل بیٹھتا ہے یا نہیں۔ ہم آپ کو دکھائیں گے کہ آپ جیسی جگہوں کے لیے ہم کس طرح کے کام کرتے ہیں — مگر جب تک ہم <em>آپ کے</em> کاروبار کو واقعی نہ سمجھ لیں، کچھ طے نہیں کریں گے۔`],
    [`We visit in person and walk your whole operation with you — finding exactly where time and money are leaking. You decide what to share, and everything stays confidential. The more you show us, the more we can help.`, `हम ख़ुद आकर आपके साथ आपके पूरे काम-काज को देखते हैं — और ठीक-ठीक पता लगाते हैं कि समय और पैसा कहाँ रिस रहा है। क्या साझा करना है, यह आप तय करते हैं, और सब कुछ गोपनीय रहता है। आप जितना दिखाएँगे, हम उतनी ज़्यादा मदद कर पाएँगे।`, `ہم خود آ کر آپ کے ساتھ آپ کے پورے کام کاج کو دیکھتے ہیں — اور ٹھیک ٹھیک پتا لگاتے ہیں کہ وقت اور پیسہ کہاں رِس رہا ہے۔ کیا شیئر کرنا ہے، یہ آپ طے کرتے ہیں، اور سب کچھ خفیہ رہتا ہے۔ آپ جتنا دکھائیں گے، ہم اتنی زیادہ مدد کر پائیں گے۔`],
    [`You see precisely what we'll do and what each piece costs, in plain numbers. You never have to touch the technology — we handle all of it. The only things we'll ask of you are the few that only you can authorize or access, and we'll walk you through those.`, `आप साफ़ आँकड़ों में ठीक-ठीक देखते हैं कि हम क्या करेंगे और हर चीज़ का क्या खर्च है। आपको टेक्नोलॉजी को छूना तक नहीं पड़ता — वह सब हम संभालते हैं। हम आपसे सिर्फ़ वही चंद चीज़ें माँगते हैं जिन्हें केवल आप ही मंज़ूरी या एक्सेस दे सकते हैं, और उनमें भी हम आपका मार्गदर्शन करते हैं।`, `آپ صاف اعداد میں ٹھیک ٹھیک دیکھتے ہیں کہ ہم کیا کریں گے اور ہر چیز کا کیا خرچ ہے۔ آپ کو ٹیکنالوجی کو چھونا تک نہیں پڑتا — وہ سب ہم سنبھالتے ہیں۔ ہم آپ سے صرف وہی چند چیزیں مانگتے ہیں جنہیں صرف آپ ہی اجازت یا رسائی دے سکتے ہیں، اور ان میں بھی ہم آپ کی رہنمائی کرتے ہیں۔`],
    [`With the right strategies you <strong>will</strong> save money and start putting money aside — that's our guarantee. How fast and how much, we estimate up front, but we won't promise a number we can't control. We take payment only after you've felt the benefit.`, `सही रणनीतियों के साथ आप पैसा बचाएँगे और पैसा अलग रखना शुरू करेंगे — यह <strong>पक्का</strong> है, हमारी गारंटी। कितनी जल्दी और कितना, इसका अंदाज़ा हम पहले ही दे देते हैं, पर जो हमारे बस में नहीं उसका वादा नहीं करते। पैसे हम तभी लेते हैं जब आप फ़ायदा महसूस कर लें।`, `صحیح حکمتِ عملیوں کے ساتھ آپ پیسہ بچائیں گے اور پیسہ الگ رکھنا شروع کریں گے — یہ <strong>پکا</strong> ہے، ہماری گارنٹی۔ کتنی جلدی اور کتنا، اس کا اندازہ ہم پہلے ہی دے دیتے ہیں، مگر جو ہمارے بس میں نہیں اس کا وعدہ نہیں کرتے۔ پیسے ہم تبھی لیتے ہیں جب آپ فائدہ محسوس کر لیں۔`],
    [`For strategy work we track month-over-month sales straight from your POS and the delivery apps — no spreadsheets, nothing massaged. Setup is a clear one-time fee. And if we connect you to a service, our fee comes from <em>you</em>, never a commission from the vendor — so the only thing we ever recommend is what's right for your restaurant. Then we agree on simple ongoing pricing to keep it all running.`, `रणनीति वाले काम के लिए हम महीने-दर-महीने की बिक्री सीधे आपके POS और डिलीवरी ऐप्स से देखते हैं — कोई एक्सेल शीट नहीं, कुछ भी इधर-उधर नहीं। सेटअप का एक साफ़ एकमुश्त शुल्क होता है। और अगर हम आपको किसी सेवा से जोड़ते हैं, तो हमारी फ़ीस <em>आपसे</em> आती है, वेंडर से कमीशन कभी नहीं — ताकि हम वही सुझाएँ जो आपके रेस्तराँ के लिए सही हो। फिर सब कुछ चलाते रहने के लिए हम आगे की आसान कीमत तय करते हैं।`, `حکمتِ عملی والے کام کے لیے ہم مہینہ بہ مہینہ فروخت سیدھے آپ کے POS اور ڈیلیوری ایپس سے دیکھتے ہیں — کوئی ایکسل شیٹ نہیں، کچھ بھی اِدھر اُدھر نہیں۔ سیٹ اپ کا ایک صاف یکمشت فیس ہوتی ہے۔ اور اگر ہم آپ کو کسی سروس سے جوڑتے ہیں، تو ہماری فیس <em>آپ سے</em> آتی ہے، وینڈر سے کمیشن کبھی نہیں — تاکہ ہم وہی تجویز کریں جو آپ کے ریستوران کے لیے صحیح ہو۔ پھر سب کچھ چلاتے رہنے کے لیے ہم آگے کی آسان قیمت طے کرتے ہیں۔`],
    [`You run the restaurant. We run the technology and the strategy behind it — and stay your team for the long run.`, `रेस्तराँ आप चलाते हैं। उसके पीछे की टेक्नोलॉजी और रणनीति हम चलाते हैं — और लंबे समय तक आपकी टीम बने रहते हैं।`, `ریستوران آپ چلاتے ہیں۔ اس کے پیچھے کی ٹیکنالوجی اور حکمتِ عملی ہم چلاتے ہیں — اور طویل عرصے تک آپ کی ٹیم بنے رہتے ہیں۔`],

    // --- refreshed: PRICING cards ---
    [`You pay only after you benefit`, `आप तभी पैसे देते हैं जब आपको फ़ायदा हो`, `آپ تبھی پیسے دیتے ہیں جب آپ کو فائدہ ہو`],
    [`Setup is a clear one-time fee. For strategy work we get paid only once the savings show up in your real numbers — tracked month over month from your POS and the apps. Month to month, no lock-in.`, `सेटअप का एक साफ़ एकमुश्त शुल्क होता है। रणनीति वाले काम के पैसे हम तभी लेते हैं जब बचत आपके असली आँकड़ों में दिखे — जो महीने-दर-महीने आपके POS और ऐप्स से देखी जाती है। महीने-दर-महीने, कोई बंधन नहीं।`, `سیٹ اپ کا ایک صاف یکمشت فیس ہوتی ہے۔ حکمتِ عملی والے کام کے پیسے ہم تبھی لیتے ہیں جب بچت آپ کے اصل اعداد میں نظر آئے — جو مہینہ بہ مہینہ آپ کے POS اور ایپس سے دیکھی جاتی ہے۔ مہینہ بہ مہینہ، کوئی پابندی نہیں۔`],
    [`No vendor commissions, ever`, `वेंडर से कमीशन कभी नहीं`, `وینڈر سے کمیشن کبھی نہیں`],
    [`If we connect you to a service, our fee comes from you — never a kickback from the vendor. So the only thing we ever recommend is what's right for your restaurant.`, `अगर हम आपको किसी सेवा से जोड़ते हैं, तो हमारी फ़ीस आपसे आती है — वेंडर से कोई कमीशन कभी नहीं। इसलिए हम वही सुझाते हैं जो आपके रेस्तराँ के लिए सही हो।`, `اگر ہم آپ کو کسی سروس سے جوڑتے ہیں، تو ہماری فیس آپ سے آتی ہے — وینڈر سے کوئی کمیشن کبھی نہیں۔ اس لیے ہم وہی تجویز کرتے ہیں جو آپ کے ریستوران کے لیے صحیح ہو۔`],

    // --- lean homepage ---
    [`Full details`, `पूरी जानकारी`, `پوری تفصیل`],
    [`Home`, `होम`, `ہوم`],
    [`How it works <span aria-hidden="true">→</span>`, `यह कैसे काम करता है <span aria-hidden="true">→</span>`, `یہ کیسے کام کرتا ہے <span aria-hidden="true">→</span>`],
    [`In plain words.`, `सीधे शब्दों में।`, `سیدھے الفاظ میں۔`],
    [`<strong>The problem:</strong> the big chains have whole departments whose only job is cutting costs, winning back customers, and planning the next move. You've got a kitchen to run and nothing left at the end of the day. So it piles up quietly: the apps take 15–30% of every order and own the customer you earned, calls go unanswered in the rush, a dozen tools and logins don't talk to each other, you can't see your real numbers, you're getting harder to find online — and there's never a spare hour to step back and fix any of it. It isn't that you're doing it wrong. You're one person against a system built for giants.`, `<strong>समस्या:</strong> बड़ी चेन के पास पूरे विभाग होते हैं जिनका इकलौता काम है — लागत घटाना, ग्राहकों को वापस लाना, और अगली चाल की योजना बनाना। आपके पास तो एक किचन चलाना है और दिन के अंत में कुछ नहीं बचता। इसलिए यह सब चुपचाप जमा होता रहता है: ऐप्स हर ऑर्डर का 15–30% ले जाते हैं और वह ग्राहक रख लेते हैं जिसे आपने कमाया, भीड़ में कॉल अनुत्तरित रह जाते हैं, दर्जनों टूल और लॉगिन आपस में बात नहीं करते, आप अपने असली आँकड़े देख नहीं पाते, ऑनलाइन आपको ढूँढना मुश्किल होता जा रहा है — और इन सबको ठीक करने के लिए पीछे हटकर सोचने का एक घंटा भी कभी नहीं मिलता। बात यह नहीं कि आप कुछ ग़लत कर रहे हैं। आप अकेले हैं, और सिस्टम बड़ों के लिए बना है।`, `<strong>مسئلہ:</strong> بڑی چینز کے پاس پورے شعبے ہوتے ہیں جن کا واحد کام ہے — لاگت گھٹانا، گاہکوں کو واپس لانا، اور اگلی چال کی منصوبہ بندی کرنا۔ آپ کے پاس تو ایک کچن چلانا ہے اور دن کے آخر میں کچھ نہیں بچتا۔ اس لیے یہ سب خاموشی سے جمع ہوتا رہتا ہے: ایپس ہر آرڈر کا 15–30% لے جاتی ہیں اور وہ گاہک رکھ لیتی ہیں جسے آپ نے کمایا، بھیڑ میں کالیں بے جواب رہ جاتی ہیں، درجنوں ٹولز اور لاگ اِن آپس میں بات نہیں کرتے، آپ اپنے اصل اعداد دیکھ نہیں پاتے، آن لائن آپ کو ڈھونڈنا مشکل ہوتا جا رہا ہے — اور اِن سب کو ٹھیک کرنے کے لیے پیچھے ہٹ کر سوچنے کا ایک گھنٹہ بھی کبھی نہیں ملتا۔ بات یہ نہیں کہ آپ کچھ غلط کر رہے ہیں۔ آپ اکیلے ہیں، اور نظام بڑوں کے لیے بنا ہے۔`],
    [`<strong>What we do:</strong> we're a restaurant family — and the tech team you could never afford to hire. From stopping the money leaking out to winning back the guests the apps keep, growing your sales, and giving you a real strategy and one clear view of your numbers — we cover it all, A to Z, setting up only the few of 100+ tools that fit you. You keep your customers, your data, and the upside.`, `<strong>हम क्या करते हैं:</strong> हम एक रेस्तराँ परिवार हैं — और वह टेक टीम जिसे आप कभी रख नहीं सकते। पैसा बाहर रिसने से रोकने से लेकर, ऐप्स के रखे ग्राहकों को वापस लाने, आपकी बिक्री बढ़ाने, और आपको एक असली रणनीति व आपके आँकड़ों की एक साफ़ तस्वीर देने तक — हम सब कुछ संभालते हैं, A से Z तक, और 100+ टूल्स में से सिर्फ़ वही चंद लगाते हैं जो आप पर सही बैठें। आपके ग्राहक, आपका डेटा और फ़ायदा — सब आपके पास।`, `<strong>ہم کیا کرتے ہیں:</strong> ہم ایک ریستوران خاندان ہیں — اور وہ ٹیک ٹیم جسے آپ کبھی رکھ نہیں سکتے۔ پیسہ باہر رِسنے سے روکنے سے لے کر، ایپس کے رکھے گاہکوں کو واپس لانے، آپ کی فروخت بڑھانے، اور آپ کو ایک اصل حکمتِ عملی اور آپ کے اعداد کی ایک صاف تصویر دینے تک — ہم سب کچھ سنبھالتے ہیں، A سے Z تک، اور 100+ ٹولز میں سے صرف وہی چند لگاتے ہیں جو آپ پر صحیح بیٹھیں۔ آپ کے گاہک، آپ کا ڈیٹا اور فائدہ — سب آپ کے پاس۔`],
    [`<strong>The deal:</strong> we come to you, show you the plan and the numbers, and do all the work. You only pay once you're saving — that's guaranteed. One free call to start.`, `<strong>तरीक़ा:</strong> हम आपके पास आते हैं, योजना और आँकड़े दिखाते हैं, और सारा काम करते हैं। पैसे आप तभी देते हैं जब आप बचत करने लगें — यह पक्का है। शुरू करने के लिए बस एक मुफ़्त कॉल।`, `<strong>طریقہ:</strong> ہم آپ کے پاس آتے ہیں، منصوبہ اور اعداد دکھاتے ہیں، اور سارا کام کرتے ہیں۔ پیسے آپ تبھی دیتے ہیں جب آپ بچت کرنے لگیں — یہ پکا ہے۔ شروع کرنے کے لیے بس ایک مفت کال۔`],
    [`We're a restaurant family first — <strong>15+ years</strong> across Canada and India, and today <strong>Wok &amp; Karahi</strong> in Spring, Texas, <strong>profitable every single year it's been open</strong> — even while 42% of restaurants aren't. Behind it: the same engineers big companies rely on. So you get the floor <em>and</em> the tech, in one partner — and <strong>we only get paid when you win</strong>.`, `हम सबसे पहले एक रेस्तराँ परिवार हैं — कनाडा और भारत में <strong>15+ साल</strong>, और आज स्प्रिंग, टेक्सस में <strong>Wok &amp; Karahi</strong>, जो <strong>हर एक साल मुनाफ़े में रहा है</strong> — जबकि 42% रेस्तराँ नहीं हैं। उसके पीछे: वही इंजीनियर जिन पर बड़ी कंपनियाँ भरोसा करती हैं। तो आपको मिलते हैं फ़्लोर <em>और</em> टेक, एक ही पार्टनर में — और <strong>पैसे हम तभी लेते हैं जब आप जीतें</strong>।`, `ہم سب سے پہلے ایک ریستوران خاندان ہیں — کینیڈا اور انڈیا میں <strong>15+ سال</strong>، اور آج اسپرنگ، ٹیکساس میں <strong>Wok &amp; Karahi</strong>، جو <strong>ہر سال منافع میں رہا ہے</strong> — جبکہ 42% ریستوران نہیں ہیں۔ اس کے پیچھے: وہی انجینئر جن پر بڑی کمپنیاں بھروسا کرتی ہیں۔ تو آپ کو ملتے ہیں فلور <em>اور</em> ٹیک، ایک ہی پارٹنر میں — اور <strong>پیسے ہم تبھی لیتے ہیں جب آپ جیتیں</strong>۔`],
    [`Five simple steps. You barely lift a finger.`, `पाँच आसान क़दम। आपको कुछ ख़ास नहीं करना पड़ता।`, `پانچ آسان قدم۔ آپ کو کچھ خاص نہیں کرنا پڑتا۔`],
    [`Tap any step for the detail — or just book the call and we'll walk you through it.`, `विस्तार के लिए किसी भी क़दम पर टैप करें — या बस कॉल बुक करें और हम आपको सब समझा देंगे।`, `تفصیل کے لیے کسی بھی قدم پر ٹیپ کریں — یا بس کال بُک کریں اور ہم آپ کو سب سمجھا دیں گے۔`],
    [`Want every detail — the plays, the 100+-tool toolbox, the pricing? <a href="details.html">See the full details →</a>`, `हर विवरण चाहिए — सारे तरीक़े, 100+ टूल्स का टूलबॉक्स, कीमत? <a href="details.html">पूरी जानकारी देखें →</a>`, `ہر تفصیل چاہیے — سارے طریقے، 100+ ٹولز کا ٹول باکس، قیمت؟ <a href="details.html">پوری تفصیل دیکھیں →</a>`],
    [`See exactly how each step works — plus the plays, the toolbox, and pricing: <a href="details.html">full details</a> · <a href="AZ-Restaurant-Partners.pdf" download="">download the PDF</a>`, `देखिए हर क़दम असल में कैसे काम करता है — साथ ही सारे तरीक़े, टूलबॉक्स और कीमत: <a href="details.html">पूरी जानकारी</a> · <a href="AZ-Restaurant-Partners.pdf" download>PDF डाउनलोड करें</a>`, `دیکھیے ہر قدم اصل میں کیسے کام کرتا ہے — ساتھ ہی سارے طریقے، ٹول باکس اور قیمت: <a href="details.html">پوری تفصیل</a> · <a href="AZ-Restaurant-Partners.pdf" download>PDF ڈاؤن لوڈ کریں</a>`],
    [`tools, 22 categories — most owners never find the few that fit. <strong>Take the free 2-minute finder — see what fits your restaurant.</strong>`, `टूल, 22 श्रेणियाँ — ज़्यादातर मालिक वही चंद कभी नहीं ढूँढ पाते जो सही बैठें। <strong>मुफ़्त 2-मिनट का फ़ाइंडर आज़माएँ — देखें आपके रेस्तराँ पर क्या सही बैठता है।</strong>`, `ٹولز، 22 زمرے — زیادہ تر مالکان وہی چند کبھی نہیں ڈھونڈ پاتے جو صحیح بیٹھیں۔ <strong>مفت 2-منٹ کا فائنڈر آزمائیں — دیکھیں آپ کے ریستوران پر کیا صحیح بیٹھتا ہے۔</strong>`],

    // --- standalone toolbox / finder page ---
    [`Free · about 2 minutes · no signup to start`, `मुफ़्त · करीब 2 मिनट · शुरू करने के लिए कोई साइनअप नहीं`, `مفت · تقریباً 2 منٹ · شروع کرنے کے لیے کوئی سائن اپ نہیں`],
    [`Find the money your restaurant is losing.`, `वह पैसा खोजें जो आपका रेस्तराँ खो रहा है।`, `وہ پیسہ تلاش کریں جو آپ کا ریستوران کھو رہا ہے۔`],
    [`There are <strong>100+ tools</strong> out there promising to fix your restaurant — and most owners have never heard of the handful that would actually move their numbers. Answer a few quick questions and we'll show you, free: <strong>what likely fits your place, what it tends to cost, and what to skip.</strong>`, `बाहर <strong>100+ टूल्स</strong> मौजूद हैं जो आपके रेस्तराँ को ठीक करने का वादा करते हैं — और ज़्यादातर मालिकों ने उन चंद टूल्स का नाम तक नहीं सुना जो वाक़ई उनके आँकड़े बदल देंगे। कुछ छोटे सवालों के जवाब दीजिए और हम मुफ़्त में बताएँगे: <strong>आप पर क्या सही बैठेगा, उसका आम तौर पर क्या खर्च होता है, और क्या छोड़ देना है।</strong>`, `باہر <strong>100+ ٹولز</strong> موجود ہیں جو آپ کے ریستوران کو ٹھیک کرنے کا وعدہ کرتے ہیں — اور زیادہ تر مالکان نے ان چند ٹولز کا نام تک نہیں سنا جو واقعی ان کے اعداد بدل دیں گے۔ کچھ مختصر سوالوں کے جواب دیجیے اور ہم مفت میں بتائیں گے: <strong>آپ پر کیا صحیح بیٹھے گا، اس کا عام طور پر کیا خرچ ہوتا ہے، اور کیا چھوڑ دینا ہے۔</strong>`],
    [`See what fits my restaurant <span aria-hidden="true">↓</span>`, `देखें मेरे रेस्तराँ पर क्या सही बैठता है <span aria-hidden="true">↓</span>`, `دیکھیں میرے ریستوران پر کیا صحیح بیٹھتا ہے <span aria-hidden="true">↓</span>`],
    [`From a restaurant family whose own place has been profitable every year it's been open — and <strong>we only get paid once you're saving</strong>.`, `एक ऐसे रेस्तराँ परिवार से जिसका अपना रेस्तराँ हर साल मुनाफ़े में रहा है — और <strong>पैसे हम तभी लेते हैं जब आप बचत करने लगें</strong>।`, `ایک ایسے ریستوران خاندان سے جس کا اپنا ریستوران ہر سال منافع میں رہا ہے — اور <strong>پیسے ہم تبھی لیتے ہیں جب آپ بچت کرنے لگیں</strong>۔`],
    [`After the finder`, `फ़ाइंडर के बाद`, `فائنڈر کے بعد`],
    [`This is just the starting map. We do the hard part.`, `यह तो बस शुरुआती नक़्शा है। मुश्किल काम हम करते हैं।`, `یہ تو بس ابتدائی نقشہ ہے۔ مشکل کام ہم کرتے ہیں۔`],
    [`<span class="steps__n">1</span> You see what fits — free, no obligation`, `<span class="steps__n">1</span> आप देखते हैं क्या सही बैठता है — मुफ़्त, बिना किसी बाध्यता`, `<span class="steps__n">1</span> آپ دیکھتے ہیں کیا صحیح بیٹھتا ہے — مفت، بغیر کسی پابندی`],
    [`<span class="steps__n">2</span> We send the full breakdown to your inbox`, `<span class="steps__n">2</span> हम पूरा ब्यौरा आपके इनबॉक्स में भेजते हैं`, `<span class="steps__n">2</span> ہم پورا تفصیلی خاکہ آپ کے اِن باکس میں بھیجتے ہیں`],
    [`<span class="steps__n">3</span> One free call — we tailor it to your place`, `<span class="steps__n">3</span> एक मुफ़्त कॉल — हम इसे आपकी जगह के हिसाब से ढालते हैं`, `<span class="steps__n">3</span> ایک مفت کال — ہم اسے آپ کی جگہ کے مطابق ڈھالتے ہیں`],
    [`<span class="steps__n">4</span> We set it all up — you only pay after you're saving`, `<span class="steps__n">4</span> हम सब कुछ सेट करते हैं — पैसे आप तभी देते हैं जब बचत होने लगे`, `<span class="steps__n">4</span> ہم سب کچھ سیٹ کرتے ہیں — پیسے آپ تبھی دیتے ہیں جب بچت ہونے لگے`],
    [`Knowing which tool to pick is the easy part. Choosing right, wiring it into your POS, and proving it actually made you money — that's what we do, end to end. <a href="index.html#how">See how it works →</a> · <a href="index.html#contact">book your free call →</a>`, `कौन-सा टूल चुनना है यह जानना आसान हिस्सा है। सही चुनना, उसे आपके POS से जोड़ना, और साबित करना कि उसने सचमुच कमाई कराई — यही हम करते हैं, शुरू से आख़िर तक। <a href="index.html#how">देखें यह कैसे काम करता है →</a> · <a href="index.html#contact">अपनी मुफ़्त कॉल बुक करें →</a>`, `کون سا ٹول چننا ہے یہ جاننا آسان حصہ ہے۔ صحیح چننا، اسے آپ کے POS سے جوڑنا، اور ثابت کرنا کہ اس نے واقعی کمائی کرائی — یہی ہم کرتے ہیں، شروع سے آخر تک۔ <a href="index.html#how">دیکھیں یہ کیسے کام کرتا ہے →</a> · <a href="index.html#contact">اپنی مفت کال بُک کریں →</a>`],
    [`<strong>Founding 5:</strong> we're hand-picking five restaurants we make money for <em>before</em> we take a dollar — founding pricing locked for life. <a href="index.html#pilot">See the pilot →</a>`, `<strong>Founding 5:</strong> हम पाँच रेस्तराँ ख़ुद चुन रहे हैं जिनके लिए हम <em>पहले</em> कमाई कराते हैं, फिर एक डॉलर लेते हैं — फ़ाउंडिंग कीमत हमेशा के लिए तय। <a href="index.html#pilot">पायलट देखें →</a>`, `<strong>Founding 5:</strong> ہم پانچ ریستوران خود چن رہے ہیں جن کے لیے ہم <em>پہلے</em> کمائی کراتے ہیں، پھر ایک ڈالر لیتے ہیں — فاؤنڈنگ قیمت ہمیشہ کے لیے طے۔ <a href="index.html#pilot">پائلٹ دیکھیں →</a>`],
    [`Know another owner getting squeezed by the apps?`, `कोई और मालिक जानते हैं जिसे ऐप्स निचोड़ रहे हैं?`, `کوئی اور مالک جانتے ہیں جسے ایپس نچوڑ رہے ہیں؟`],
    [`Send them this finder <span aria-hidden="true">→</span>`, `उन्हें यह फ़ाइंडर भेजें <span aria-hidden="true">→</span>`, `انہیں یہ فائنڈر بھیجیں <span aria-hidden="true">→</span>`],
  ];

  const TX = { hi: {}, ur: {} };
  ROWS.forEach(([e, h, u]) => { const k = norm(e); if (h) TX.hi[k] = h; if (u) TX.ur[k] = u; });

  const SEL = [
    '.nav__links a',
    '.hero .kicker', '.hero__title', '.hero__lead', '.hero__cta a', '.portrait__tag',
    '.creds__item strong', '.creds__item span',
    '.band .h2', '.band .lead', '.band__list li',
    '.stat span',
    '.ctaband p', '.ctaband a',
    '#how .kicker', '#how .h2', '#how .section__head .lead', '.lifecycle li h3', '.lifecycle li p', '.steps summary', '.steps details > p', '.steplist li', '.promise',
    '.story .kicker', '.story .h2', '.story__p', '.story__photo figcaption', '.quote__text', '.quote__by',
    '#possible .section__head .kicker', '#possible .section__head .h2', '#possible .section__head .lead',
    '.who__label', '.who__opt',
    '#possible .poss h3', '#possible .poss > p',
    '.possible__more', '#possible .possible__cta', '#how .possible__cta',
    '#finder .kicker', '#finder .h2', '#finder .section__head .lead',
    '#faq .kicker', '#faq .h2', '.faq summary', '.faq details > p',
    '#pricing .section__head .kicker', '#pricing .section__head .h2', '#pricing .section__head .lead',
    '#pricing .poss h3', '#pricing .poss > p',
    '.pilot__tag', '.pilot h3', '.pilot p', '.pilot a',
    '#pricing .possible__cta',
    '#contact .kicker', '#contact .h2', '#contact .lead',
    '.contact__list li span',
    '.form label > span', '#formSubmit', '.form__note',
    '.footer__inner p:not(.footer__copy)',
    '.toolbox-trigger__txt',
    '.tbhero .kicker', '.tbhero__title', '.tbhero__sub', '.tbhero__lead', '.tbhero__btn', '.tbhero__trust',
    '#tbnext .kicker', '#tbnext .h2', '#tbnext .possible__cta', '.tb-scarcity',
    '.tb-share__txt', '.tb-share__btn',
    '.mobilecta a',
  ].join(', ');

  // Dynamic strings used by script.js (persona toggle + finder hint)
  const PERSONA = {
    en: {
      p1: `For a single neighborhood spot, the fastest money is defensive: turn the customers the apps bring you into your own repeat orders, get every call answered, and end the tablet chaos — wins you feel within weeks. <strong>Start with the three marked below.</strong>`,
      p2: `For an established family restaurant, the money is in your regulars and your reputation: bring lapsed guests back, lift your reviews, and grow a higher-margin catering channel. <strong>Start with the three marked below.</strong>`,
      p3: `For 2–10 locations, it's visibility and consistency: recover what the apps owe you across stores, get found everywhere new guests look, and win the customers the apps send you. <strong>Start with the three marked below.</strong>`,
    },
    hi: {
      p1: `एक मोहल्ले की छोटी जगह के लिए, सबसे जल्दी पैसा बचाव में है: ऐप के लाए ग्राहकों को अपने बार-बार के ऑर्डर में बदलें, हर कॉल का जवाब दें, और टैबलेट की अफ़रा-तफ़री ख़त्म करें — फ़ायदा हफ़्तों में दिखेगा। <strong>नीचे चिह्नित तीन से शुरू करें।</strong>`,
      p2: `एक जमे-जमाए फ़ैमिली रेस्तराँ के लिए, पैसा आपके नियमित ग्राहकों और साख में है: छूटे ग्राहक वापस लाएँ, रिव्यू बढ़ाएँ, और ज़्यादा मुनाफ़े वाला कैटरिंग चैनल बढ़ाएँ। <strong>नीचे चिह्नित तीन से शुरू करें।</strong>`,
      p3: `2–10 लोकेशन के लिए, बात है साफ़ नज़र और एकरूपता की: सब दुकानों में ऐप्स का बकाया वसूलें, जहाँ नए ग्राहक देखते हैं वहाँ मिलें, और ऐप के भेजे ग्राहकों को जीतें। <strong>नीचे चिह्नित तीन से शुरू करें।</strong>`,
    },
    ur: {
      p1: `محلے کی ایک چھوٹی جگہ کے لیے، سب سے جلدی پیسہ بچاؤ میں ہے: ایپ کے لائے گاہکوں کو اپنے بار بار کے آرڈر میں بدلیں، ہر کال کا جواب دیں، اور ٹیبلٹ کی افراتفری ختم کریں — فائدہ ہفتوں میں نظر آئے گا۔ <strong>نیچے نشان زدہ تین سے شروع کریں۔</strong>`,
      p2: `ایک جمے جمائے فیملی ریستوران کے لیے، پیسہ آپ کے مستقل گاہکوں اور ساکھ میں ہے: چھوٹے گاہک واپس لائیں، ریویوز بڑھائیں، اور زیادہ منافع والا کیٹرنگ چینل بڑھائیں۔ <strong>نیچے نشان زدہ تین سے شروع کریں۔</strong>`,
      p3: `2–10 مقامات کے لیے، بات ہے صاف نظر اور یکسانیت کی: سب دکانوں میں ایپس کا واجب وصول کریں، جہاں نئے گاہک دیکھتے ہیں وہاں ملیں، اور ایپ کے بھیجے گاہکوں کو جیتیں۔ <strong>نیچے نشان زدہ تین سے شروع کریں۔</strong>`,
    },
  };
  const FINDER_HINT = {
    en: { p: `Set the sentence above to match your place — then see what fits.`, btn: `See what fits my restaurant →` },
    hi: { p: `ऊपर का वाक्य अपनी जगह के हिसाब से सेट करें — फिर देखें क्या सही बैठता है।`, btn: `देखें मेरे रेस्तराँ पर क्या सही बैठता है →` },
    ur: { p: `اوپر کا جملہ اپنی جگہ کے مطابق سیٹ کریں — پھر دیکھیں کیا صحیح بیٹھتا ہے۔`, btn: `دیکھیں میرے ریستوران پر کیا صحیح بیٹھتا ہے →` },
  };

  window.AZL = { lang: 'en', persona: PERSONA, finderHint: FINDER_HINT };

  function translate(lang) {
    document.querySelectorAll(SEL).forEach((el) => {
      if (el.dataset.en === undefined) el.dataset.en = el.innerHTML;
      const key = norm(el.dataset.en);
      el.innerHTML = (lang === 'en') ? el.dataset.en : (TX[lang][key] || el.dataset.en);
    });
  }

  function setLang(lang) {
    window.AZL.lang = lang;
    translate(lang);
    const html = document.documentElement;
    html.setAttribute('lang', lang);
    html.setAttribute('dir', lang === 'ur' ? 'rtl' : 'ltr');
    html.classList.toggle('lang-hi', lang === 'hi');
    html.classList.toggle('lang-ur', lang === 'ur');
    document.querySelectorAll('#lang .lang__opt').forEach((b) => b.classList.toggle('is-active', b.dataset.lang === lang));
    try { localStorage.setItem('azlang', lang); } catch (e) {}
    window.dispatchEvent(new CustomEvent('azlang', { detail: lang }));
  }
  window.AZsetLang = setLang;

  const init = () => {
    document.querySelectorAll('#lang .lang__opt').forEach((b) => b.addEventListener('click', () => setLang(b.dataset.lang)));
    let saved = 'en';
    try { saved = localStorage.getItem('azlang') || 'en'; } catch (e) {}
    setLang(saved);
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
